// Package artifacts loads authored team files from a workspace.
package artifacts

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/manuel/miez-cli/internal/model"
	"gopkg.in/yaml.v3"
)

const (
	// TeamIndexFileName is the generated install-time team catalog.
	TeamIndexFileName = "miez.generated.yaml"
	// GeneratedTeamIndexHeader warns authors not to edit the generated catalog.
	GeneratedTeamIndexHeader = "# Generated by miez team build. DO NOT EDIT.\n"
)

// TeamDir is a loaded team and its source directory.
type TeamDir struct {
	Root string
	Team model.Team
}

// LoadTeam reads and validates the manifest shape from a team directory.
func LoadTeam(root string) (TeamDir, error) {
	manifestPath := filepath.Join(root, TeamIndexFileName)
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return TeamDir{}, fmt.Errorf("read %s: %w", manifestPath, err)
	}

	var team model.Team
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&team); err != nil {
		return TeamDir{}, fmt.Errorf("parse %s: %w", manifestPath, err)
	}
	return TeamDir{Root: root, Team: team}, nil
}

// LoadAll discovers team directories below a modules root.
func LoadAll(root string) ([]TeamDir, error) {
	entries, err := os.ReadDir(root)
	if errors.Is(err, os.ErrNotExist) {
		return []TeamDir{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read modules: %w", err)
	}

	teams := make([]TeamDir, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		team, err := LoadTeam(filepath.Join(root, entry.Name()))
		if err != nil {
			return nil, err
		}
		teams = append(teams, team)
	}
	return teams, nil
}

// ReadWorker reads one worker Markdown artifact.
func (team TeamDir) ReadWorker(worker model.Worker) (Markdown, error) {
	return readMarkdown(team.Root, worker.Path, worker.ID)
}

// ReadSkill reads a skill Markdown artifact by id.
func (team TeamDir) ReadSkill(skillID string) (Markdown, error) {
	if !model.IsValidIdentifier(skillID) {
		return Markdown{}, fmt.Errorf("invalid skill id %q", skillID)
	}
	path := filepath.Join("skills", skillID, "SKILL.md")
	if skill, ok := team.Team.Skill(skillID); ok {
		path = skill.Path
	} else {
		return Markdown{}, fmt.Errorf("skill %q is not declared in %s", skillID, TeamIndexFileName)
	}
	return readMarkdown(team.Root, path, skillID)
}

// ReadWorkflow reads one workflow Markdown artifact using its generated
// catalog path and verifies that its frontmatter identity still matches.
func (team TeamDir) ReadWorkflow(workflow model.Workflow) (Markdown, error) {
	if workflow.Path == "" {
		return Markdown{}, fmt.Errorf("workflow %q has no source path", workflow.ID)
	}
	return readMarkdown(team.Root, workflow.Path, workflow.ID)
}

// Markdown contains frontmatter and body content from an authored file.
type Markdown struct {
	ID       string
	Body     string
	Metadata map[string]any
}

// IDFromPath derives the artifact identity from its location: a skill id is
// its skills/<skill-id>/ directory name, worker and workflow ids are the
// Markdown file name without extension.
func IDFromPath(relativePath string) string {
	base := filepath.Base(filepath.FromSlash(relativePath))
	if base == "SKILL.md" {
		return filepath.Base(filepath.Dir(filepath.FromSlash(relativePath)))
	}
	return strings.TrimSuffix(base, filepath.Ext(base))
}

func readMarkdown(root, relativePath, expectedID string) (Markdown, error) {
	cleanPath, err := safeRelativePath(relativePath)
	if err != nil {
		return Markdown{}, err
	}
	path := filepath.Join(root, cleanPath)
	info, err := os.Lstat(path)
	if err != nil {
		return Markdown{}, fmt.Errorf("stat %s: %w", path, err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return Markdown{}, fmt.Errorf("artifact %s must not be a symlink", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return Markdown{}, fmt.Errorf("read %s: %w", path, err)
	}
	markdown, err := parseMarkdown(data)
	if err != nil {
		return Markdown{}, fmt.Errorf("parse %s: %w", path, err)
	}
	markdown.ID = IDFromPath(cleanPath)
	if expectedID != "" && markdown.ID != expectedID {
		return Markdown{}, fmt.Errorf("%s file name implies id %q, want %q", path, markdown.ID, expectedID)
	}
	return markdown, nil
}

// ReadMarkdown reads one safe Markdown artifact without requiring a catalog
// identity. Builders use it to inspect authored frontmatter before generating
// the team index.
func ReadMarkdown(root, relativePath string) (Markdown, error) {
	return readMarkdown(root, relativePath, "")
}

func parseMarkdown(data []byte) (Markdown, error) {
	const delimiter = "---"
	trimmed := bytes.TrimSpace(data)
	if !bytes.HasPrefix(trimmed, []byte(delimiter)) {
		return Markdown{}, errors.New("missing YAML frontmatter")
	}

	rest := trimmed[len(delimiter):]
	separator := bytes.Index(rest, []byte("\n---"))
	if separator < 0 {
		return Markdown{}, errors.New("unterminated YAML frontmatter")
	}

	frontmatter := bytes.TrimSpace(rest[:separator])
	body := bytes.TrimSpace(rest[separator+len("\n---"):])
	metadata := map[string]any{}
	if err := yaml.Unmarshal(frontmatter, &metadata); err != nil {
		return Markdown{}, fmt.Errorf("frontmatter: %w", err)
	}
	if _, ok := metadata["id"]; ok {
		return Markdown{}, errors.New("frontmatter field \"id\" is not allowed; the id is derived from the file name")
	}
	return Markdown{Body: string(body), Metadata: metadata}, nil
}

func safeRelativePath(value string) (string, error) {
	if strings.TrimSpace(value) == "" {
		return "", errors.New("artifact path must not be empty")
	}
	clean := filepath.Clean(filepath.FromSlash(value))
	if !filepath.IsLocal(clean) || clean == "." {
		return "", fmt.Errorf("artifact path %q escapes the team directory", value)
	}
	return clean, nil
}

// FilesExist checks the manifest-referenced files without loading their body.
func (team TeamDir) FilesExist() error {
	for _, skill := range team.Team.Skills {
		if _, err := team.ReadSkill(skill.ID); err != nil {
			return err
		}
	}
	for _, worker := range team.Team.Workers {
		if _, err := os.Stat(filepath.Join(team.Root, filepath.FromSlash(worker.Path))); err != nil {
			return fmt.Errorf("worker %q path %q: %w", worker.ID, worker.Path, err)
		}
		for _, skill := range worker.Skills {
			path := filepath.Join(team.Root, "skills", skill, "SKILL.md")
			if _, err := os.Stat(path); err != nil {
				return fmt.Errorf("worker %q skill %q: %w", worker.ID, skill, err)
			}
		}
	}
	for _, workflow := range team.Team.Workflows {
		if _, err := team.ReadWorkflow(workflow); err != nil {
			return err
		}
	}
	return nil
}

// WalkMarkdown returns all authored Markdown files, useful for bootstrap and
// future contract checks.
func (team TeamDir) WalkMarkdown() ([]string, error) {
	paths := []string{}
	err := filepath.WalkDir(team.Root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}
		relative, err := filepath.Rel(team.Root, path)
		if err != nil {
			return err
		}
		paths = append(paths, filepath.ToSlash(relative))
		return nil
	})
	return paths, err
}

// CopyDirectory copies a validated artifact directory without following
// symlinks or copying special files.
func CopyDirectory(ctx context.Context, source, destination string) error {
	return filepath.Walk(source, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("downloaded team contains unsupported symlink %q", path)
		}
		relative, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		target := filepath.Join(destination, relative)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("downloaded team contains unsupported file %q", path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}

// WalkFiles returns every regular file below root, relative to root, sorted
// and slash-separated. Used to compute a team's deployed file list.
func WalkFiles(root string) ([]string, error) {
	paths := []string{}
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		paths = append(paths, filepath.ToSlash(relative))
		return nil
	})
	return paths, err
}
